### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by wisdom22323** [arthurdjn/nets#2]
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/0000/.local/lib/python3.6/site-packages/nets/__init__.py", line 5, in <module>
    from nets.autograd import Hook, Parameter
  File "/home/0000/.local/lib/python3.6/site-packages/nets/autograd/__init__.py", line 3, in <module>
    from .functional import *
  File "/home/0000/.local/lib/python3.6/site-packages/nets/autograd/functional.py", line 15, in <module>
    import nets.autograd.function as fc
AttributeError: module 'nets' has no attribute 'autograd'

**Comment by wisdom22323** [comment]
versions of nets = 0.0.3.1

**Comment by arthurdjn** [comment]
Thank you for your interest in this package. 

The package works on different version of Ubuntu (tested on 16, 18, 20) and windows 7 and 10. It also works on Google Colaboratory. 
I think your installation is broken, you should use `pip install nets` to install it. You may need to upgrade `pip` or install a newer version of Python. 

You can test `nets` on [Google Colab here](https://colab.research.google.com/drive/16iQGE0RwuwsBEPp0YSeQOgvM8Vq2-hpo?usp=sharing) or open the provided notebooks with colaboratory.

Also, please provide more information on your setup, like how did you installed this package. With the provided information, it is difficult to debug your specific issue.
